train_dataset_path: 'dataset/train'
validation_dataset_path: 'dataset/validation'
device_name: 'mps'
batch_size: 8
num_epochs: 2
shuffle_queue_size: 16
checkpoint_file: './tools/checkpoint.pth'
output_file: './tools/output.pth'
model_config:
  num_layers: 2
  max_degree: 1
  feature_dim: 4
  num_modes: 2
  num_heads: 1